sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 8179145355932
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5t5ZhFVZ2BDnbRDZyLEm
    access-key-secret: CD1gNG45HO8A1u1wZeydRx021dDGAC
    bucket-name: seatide-sky-take-out